In [1]:
# Series 
# Similar to numpy but series can have labels 
# So can be indexed by the labels.

In [2]:
import numpy as np 
import pandas as pd

In [3]:
labels = ['a', 'b', 'c']
my_list = [10, 20, 30]
arr = np.array([10, 20, 30])
d = {'a': 10, 'b': 20, 'c': 30}

In [4]:
pd.Series(data = my_list)

0    10
1    20
2    30
dtype: int64

In [5]:
pd.Series(data=my_list, index=labels)

a    10
b    20
c    30
dtype: int64

In [6]:
pd.Series(my_list, labels)

a    10
b    20
c    30
dtype: int64

In [7]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [8]:
pd.Series(arr, labels)

a    10
b    20
c    30
dtype: int64

In [9]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [10]:
# Using index 
ser1 = pd.Series([1,2,3,4], index = ['USA', 'CHINA', 'GHANA', 'SCOTLAND'])

In [11]:
ser1

USA         1
CHINA       2
GHANA       3
SCOTLAND    4
dtype: int64

In [12]:
ser2 = pd.Series([1, 2, 5, 4], index = ['USA', 'CHINA', 'TOGO', 'NIGERIA'])
ser2

USA        1
CHINA      2
TOGO       5
NIGERIA    4
dtype: int64

In [13]:
ser1['USA']

1

In [14]:
ser1 + ser2

CHINA       4.0
GHANA       NaN
NIGERIA     NaN
SCOTLAND    NaN
TOGO        NaN
USA         2.0
dtype: float64

In [15]:
# DATAFRAMES 
from numpy.random import randn 
np.random.seed(101)

In [16]:
df = pd.DataFrame(randn(5, 4), index = 'A B C D E'.split(), columns='W X Y Z'.split())

In [17]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [18]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [20]:
df[['W', 'Z']]

          W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [21]:
df.W

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [22]:
df['new'] = df['W'] + df['Y']

In [23]:
df

          W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [24]:
# drop column 
df.drop('new', axis=1)

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [25]:
df

          W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [26]:
# truely remove column 
df.drop('new', axis=1, inplace=True)

In [27]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [28]:
# Selecting Rows 
df.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [29]:
df.iloc[2]

W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64

In [30]:
# Selecting subset of rows and columns 
df.loc['B', 'Y']

-0.8480769834036315

In [31]:
df.loc[['A', 'B'], ['W', 'Y']]

          W         Y
A  2.706850  0.907969
B  0.651118 -0.848077

In [32]:
# Conditional Selection 
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [34]:
df > 0

       W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [35]:
df < 0

       W      X      Y      Z
A  False  False  False  False
B  False   True   True  False
C   True  False  False   True
D  False   True   True  False
E  False  False  False  False

In [36]:
df[df > 0]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [37]:
df[df['W'] > 0]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [38]:
df[df['W'] > 0]['Y']

A    0.907969
B   -0.848077
D   -0.933237
E    2.605967
Name: Y, dtype: float64

In [39]:
df[df['W'] > 0][['Y', 'X']]

          Y         X
A  0.907969  0.628133
B -0.848077 -0.319318
D -0.933237 -0.758872
E  2.605967  1.978757

In [40]:
df[(df['W'] > 0) & (df['Y'] > 1)]

          W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

In [41]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [42]:
df.reset_index()

  index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [43]:
newStates = 'AS GR BA CR WR'.split()

In [44]:
df['States'] = newStates

In [45]:
df

          W         X         Y         Z States
A  2.706850  0.628133  0.907969  0.503826     AS
B  0.651118 -0.319318 -0.848077  0.605965     GR
C -2.018168  0.740122  0.528813 -0.589001     BA
D  0.188695 -0.758872 -0.933237  0.955057     CR
E  0.190794  1.978757  2.605967  0.683509     WR

In [46]:
df.set_index('States')

               W         X         Y         Z
States
AS      2.706850  0.628133  0.907969  0.503826
GR      0.651118 -0.319318 -0.848077  0.605965
BA     -2.018168  0.740122  0.528813 -0.589001
CR      0.188695 -0.758872 -0.933237  0.955057
WR      0.190794  1.978757  2.605967  0.683509

In [47]:
df

          W         X         Y         Z States
A  2.706850  0.628133  0.907969  0.503826     AS
B  0.651118 -0.319318 -0.848077  0.605965     GR
C -2.018168  0.740122  0.528813 -0.589001     BA
D  0.188695 -0.758872 -0.933237  0.955057     CR
E  0.190794  1.978757  2.605967  0.683509     WR

In [48]:
df.set_index('States', inplace=True)

In [49]:
df

               W         X         Y         Z
States
AS      2.706850  0.628133  0.907969  0.503826
GR      0.651118 -0.319318 -0.848077  0.605965
BA     -2.018168  0.740122  0.528813 -0.589001
CR      0.188695 -0.758872 -0.933237  0.955057
WR      0.190794  1.978757  2.605967  0.683509

In [50]:
# GroupBy

In [51]:
data = {
    'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]

}

In [52]:
df = pd.DataFrame(data)

In [53]:
df

  Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [57]:
by_comp = df.groupby('Company')

In [58]:
by_comp

In [59]:
by_comp.mean()

         Sales
Company
FB       296.5
GOOG     160.0
MSFT     232.0

In [60]:
by_comp.std()

              Sales
Company
FB        75.660426
GOOG      56.568542
MSFT     152.735065

In [61]:
by_comp.min()

          Person  Sales
Company
FB          Carl    243
GOOG     Charlie    120
MSFT         Amy    124

In [62]:
by_comp.max()

          Person  Sales
Company
FB         Sarah    350
GOOG         Sam    200
MSFT     Vanessa    340

In [63]:
by_comp.describe()

        Sales
        count   mean         std    min     25%    50%     75%    max
Company
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [64]:
# MERGING, JOINING AND CONCATENATING

In [65]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])

In [66]:
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [67]:
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7]) 
df2

    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [68]:
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])
df3

      A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [70]:
pd.concat([df1, df2, df3])

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [71]:
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
   
right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                          'C': ['C0', 'C1', 'C2', 'C3'],
                          'D': ['D0', 'D1', 'D2', 'D3']})

In [72]:
left

  key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3

In [73]:
right

  key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3

In [74]:
# Merging

In [75]:
pd.merge(left, right, how="inner", on="key")

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [78]:
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})
    
right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                               'key2': ['K0', 'K0', 'K0', 'K0'],
                                  'C': ['C0', 'C1', 'C2', 'C3'],
                                  'D': ['D0', 'D1', 'D2', 'D3']})

In [81]:
pd.merge(left, right, on=["key1", "key2"])

  key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

In [82]:
# Joining

In [85]:
left = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                      index=['K0', 'K1', 'K2']) 

right = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                    'D': ['D0', 'D2', 'D3']},
                      index=['K0', 'K2', 'K3'])

In [86]:
left.join(right)

     A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [87]:
left.join(right, how="outer")

      A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3  NaN  NaN   C3   D3